#!/usr/bin/env python3
from datetime import datetime
from itertools import islice
from urllib.request import urlopen
from xml.etree import ElementTree


def get_articles() -> list[str]:
    with urlopen('https://qsantos.fr/feed/') as f:
        rss = f.read()
    root = ElementTree.fromstring(rss.decode())
    for item in root.iter('item'):
        title = item.find('title').text
        link = item.find('link').text
        pubDate = item.find('pubDate').text
        pubDate = datetime.strptime(pubDate, '%a, %d %b %Y %H:%M:%S %z').strftime('%Y-%m-%d')
        yield title, link, pubDate


def generate_readme(latest_articles: str) -> None:
    with open('README.md.template') as f:
        template = f.read()
    contents = template.replace('{{LATEST_ARTICLES}}', latest_articles)
    with open('README.md', 'w') as f:
        f.write(contents)


def main() -> None:
    latest_articles = '\n'.join(
        f'- `{pubDate}` [{title}]({link})'
        for title, link, pubDate in islice(get_articles(), 5)
    )
    generate_readme(latest_articles)


if __name__ == '__main__':
    main()
